export const homes = [
  {
    id: 1,
    location: "123 Main St, Anytown, USA",
    owner: "John Smith",
    status: "for sale",
    price: "$500,000",
    picture: "/images/1.jfif",
    numberOfRatings: 10,
    rating: Math.floor(Math.random() * 6), // generates a random integer between 0 and 5
  },
  {
    id: 2,
    location: "456 Oak St, Anytown, USA",
    owner: "Jane Doe",
    status: "for rent",
    price: "$2,500/month",
    picture: "/images/2.jfif",
    numberOfRatings: 5,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 3,
    location: "789 Elm St, Anytown, USA",
    owner: "Bob Johnson",
    status: "for sale",
    price: "$750,000",
    picture: "images/3.jfif",
    numberOfRatings: 8,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 4,
    location: "321 Maple Ave, Anytown, USA",
    owner: "Samantha Lee",
    status: "for rent",
    price: "$3,000/month",
    picture: "images/4.jfif",
    numberOfRatings: 12,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 5,
    location: "654 Pine St, Anytown, USA",
    owner: "Michael Chen",
    status: "for sale",
    price: "$600,000",
    picture: "images/5.jfif",
    numberOfRatings: 3,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 6,
    location: "987 Cedar Rd, Anytown, USA",
    owner: "Lisa Rodriguez",
    status: "for rent",
    price: "$2,200/month",
    picture: "images/6.jfif",
    numberOfRatings: 7,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 7,
    location: "246 Juniper Ln, Anytown, USA",
    owner: "Dav Kim",
    status: "for sale",
    price: "$850,000",
    picture: "images/7.jfif",
    numberOfRatings: 2,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 8,
    location: "369 Birch Blvd, Anytown, USA",
    owner: "Emily Nguyen",
    status: "for rent",
    price: "$2,800/month",
    picture: "images/8.jfif",
    numberOfRatings: 9,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 9,
    location: "582 Ash St, Anytown, USA",
    owner: "William Jones",
    status: "for sale",
    price: "$550,000",
    picture: "images/9.jfif",
    numberOfRatings: 4,
    rating: Math.floor(Math.random() * 6),
  },
  {
    id: 10,
    location: "741 Cherry Ave, Anytown, USA",
    owner: "Sarah Davis",
    status: "for rent",
    price: "$2,500/month",
    picture: "images/10.jfif",
    numberOfRatings: 23,
    rating: Math.floor(Math.random() * 6),
  },
];
